### ISSUE TITLE
Block device creation in  a non-existent/not started volume causes a silent failure

### ISSUE THREAD

**Issue by vbellur** [gluster/gluster-block#10]
Block device creation in  a non-existent/not started volume causes a silent failure:

#gluster-block create rep2/bd1 ha 3 10.16.153.48,10.16.153.51,10.16.153.54 100GiB
# echo $?
255

It would be necessary to display a graceful failure message upon not finding a volume in the CLI output.

**Comment by pkalever** [comment]
Open for review:
https://review.gluster.org/#/c/16992/
