### ISSUE TITLE
Metrics for monitoring

### ISSUE THREAD

**Issue by pranithk** [gluster/gluster-block#106]
I am raising this issue to figure out the metrics that need to be tracked from gluster-block projects so that it is easier to monitor that gluster-block is functioning as expected.

@pkalever @lxbsz @bgoyal please let me know. We are coming up with infra so that these metrics are stored at regular intervals so that when a user/customer hits any issue you have historic data about the deployment which will help to resolve the issue sooner.

**Comment by pkalever** [comment]
Won't Fix, closing now.
