### ISSUE TITLE
Prevent configuration errors when sparse files exist in block-store

### ISSUE THREAD

**Issue by pranithk** [gluster/gluster-block#116]
Say, if the block hosting volume is 100% used, we expect the block volume delete
operation should free some space. But since the delete operation will also incur
some metadata writes into the respective block meta file, the meta writes will
fail with ENOSPC. Hence the block delete operation will be terminated. This is addressed for cases without sparse files with https://github.com/gluster/gluster-block/pull/112, but we need to solve this even for sparse file case. Raising this issue to track that.

**Comment by pkalever** [comment]
Not a priority, for now, we are recommending to shrink the backend file manually and getting this worked around. Feel free to open it or send a PR to automate this. Closing this for now.
