### ISSUE TITLE
Dump all failure cli responses to stderr

### ISSUE THREAD

**Issue by pkalever** [gluster/gluster-block#117]
On FAILURE dump reply.out to stderr
On SUCCESS dump reply.out to stdout

**Comment by pranithk** [comment]
@pkalever Traditionally applications dump to stderr on Failure and stdout on success, wondering what prompted you to dump to stderr even on success.

**Comment by pranithk** [comment]
@pkalever Didn't get you. Are you saying On SUCCESS we dump it on stdout? Issue description says: " On SUCCESS dump reply.out to stderr"

**Comment by pkalever** [comment]
> @pkalever Didn't get you. Are you saying On SUCCESS we dump it on stdout? Issue description says: " On SUCCESS dump reply.out to stderr"

Ah! sorry. Just corrected. Thanks!
