### ISSUE TITLE
LIO/TCMU Ringbuffer's cmd_time_out is not working

### ISSUE THREAD

**Issue by lxbsz** [gluster/gluster-block#126]
Currently there has one cmd timeout timer for each udev in kernel space, and whenever there has any new coming cmd it will update the timer. And for some corner case the timer is always working only for the ringbuffer's newest cmd. That's to say the timer won't be fired even there has one cmd stuck for a very long time.

**Comment by lxbsz** [comment]
Patchv1:  https://www.spinics.net/lists/linux-scsi/msg123393.html

Patchv2:  https://patchwork.kernel.org/patch/10607127/

**Comment by lxbsz** [comment]
Patchv4: https://www.spinics.net/lists/target-devel/msg17361.html

**Comment by pkalever** [comment]
@lxbsz looks like this is fixed now. Can we close this ?

**Comment by lxbsz** [comment]
> @lxbsz looks like this is fixed now. Can we close this ?

Yeah, we need to downstream it to RHEL zstream. I will do it later.
