### ISSUE TITLE
Provide an option to fetch the volume info from different place, other than 'localhost'.

### ISSUE THREAD

**Issue by amarts** [gluster/gluster-block#136]
In `glfs-operations.c` we have below line:

```
rpc/glfs-operations.c:  ret = glfs_set_volfile_server(glfs, "tcp", "localhost", 24007);
```

For keeping the sanity, we should 'default' to localhost:24007, but user should have an option to fetch the details for the Block Hosting volume from different IP (or hostname). That would allow us to separately host gluster-block from glusterfs bricks, where there is glusterd running.

**Comment by pkalever** [comment]
Fixed-by: https://github.com/gluster/gluster-block/pull/161
