### ISSUE TITLE
Gluster-block command doesn't errors out or gives message when the gluster-blockd service is not running on the node

### ISSUE THREAD

**Issue by sbhaloth** [gluster/gluster-block#14]
Description of problem:
*******************************
When gluster-blockd service is not running on a system then if a gluster-block command is executed it doesn't errors out or give message about service not running.

systemctl status gluster-blockd
● gluster-blockd.service - Gluster block storage utility
   Loaded: loaded (/usr/lib/systemd/system/gluster-blockd.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
[root@dhcp46-63 gluster-block]# gluster-block list blockstor

gluster-block-0.1.1-1.x86_64

How reproducible:
Always

Steps to Reproduce:
1. Stop gluster-block service on any node 
2. execute gluster-block command e.g gluster-block list volname
3. Check the output

Actual results:
*************************
The command just runs and does not gives any output in form of error message.

Expected results:
**************************
The command should fail telling gluster-blockd service is not running.

Additional info:

**Comment by pkalever** [comment]
Available for review: https://review.gluster.org/#/c/17120/
please-review: @pranithk @nixpanic @vbellur
