### ISSUE TITLE
block create: default prealloc to full, for better performance

### ISSUE THREAD

**Issue by pkalever** [gluster/gluster-block#149]
As of now prealloc is off by default. Should we rather default prealloc to full by default for better user experience ? 

@pranithk @vbellur @amarts @nixpanic @obnoxxx @lxbsz thoughts ?

Thanks!

**Comment by lxbsz** [comment]
If on it by default, in the future the thin provision device supporting won't be a problem ? And also, the prealloc to full option will cost a longer time for the device's creation, will this be a problem for some cases like there are thousands of pods/contianers creation/deletion per second ?

**Comment by nixpanic** [comment]
As Xiubo mentions, thin-provisioning is something that must be supportable in the future. Defaulting to pre-allocation is now done through Heketi (I think). Not sure how the integration in GD2 looks like, but that should be flexible as well. Good defaults are important, but there need to be ways to request non-default options.

**Comment by pranithk** [comment]
@pkalever +1 from me. Consdering the only usecase for gluster-block is using heketi which creates gluster-block devices with pre-allocation, that seems like a better default than what we have now.

**Comment by JohnStrunk** [comment]
- What does "better performance" mean?
  - Random or sequential?
  - 1st write or overwrite?
  - Does the storage media affect whether this is of benefit (hdd/ssd)?
- What is the effect on volume create?
  - Does it change the rate of volume creation?
  - Does it change the latency of creating a 1 TB volume?
- How would this change affect our ability to do thin provisioning in GCS through thin_p, loop mounted files, and/or VDO?

**Comment by inevity** [comment]
For EC volume which did not support zerofill op , if run create cmd with prealloc full,the command will fail, 
So it is sensible to let use to supply the value?

**Comment by nixpanic** [comment]
On Thu, Apr 18, 2019 at 01:38:10AM -0700, baul wrote:
> For EC volume which did not support zerofill op , if run create cmd with prealloc full,the command will fail, 
> So it is sensible to let use to supply the value?

EC/disperse does still not support zerofill. I expected that
gluster-block does a fallback when it errors out. This should be the
case for tcmu-runner as well... If some operations trigger
glfs_zerofill(), those will all fail on EC/disperse volymes.

I am not sure if fallbacks are in place everywhere, so it may not be
sufficient to turn off prealloc on creation.

**Comment by pkalever** [comment]
> On Thu, Apr 18, 2019 at 01:38:10AM -0700, baul wrote: For EC volume which did not support zerofill op , if run create cmd with prealloc full,the command will fail, So it is sensible to let use to supply the value?
> EC/disperse does still not support zerofill. I expected that gluster-block does a fallback when it errors out. This should be the case for tcmu-runner as well... If some operations trigger glfs_zerofill(), those will all fail on EC/disperse volymes. I am not sure if fallbacks are in place everywhere, so it may not be sufficient to turn off prealloc on creation.

To confirm, at the moment fallback mechanism is not in-place.

But I'm doubtful that silently falling back to prealloc-off could be an issue ?

As users might see additional free space on these BHV volumes, when calculating the space usage b/w zerofill supported volumes and non-supported volume and might wonder about the diff.


@nixpanic @amarts @lxbsz @pranithk @inevity Do we have some preference b/w:

1. throw a meaningful error on glfs_zerofill failures, something like:
```
# gluster-block create EC-vol/block 192.168.0.5 prealloc on 1GiB
'prealloc full' not supported on EC/disperse block hosting volumes, please pass 'prealloc off'

```
then fail the create command and let the user take care of passing 'prealloc off' in the next command.

and

2. dump a msg in logs and stdout about fall back on zerofill failure and continue with block create without failure ?

Thoughts ?

Thanks!

**Comment by nixpanic** [comment]
I suggest to log the failure of `glfs_zerofill()` and in case it is `ENOTSUP` do a slow write of all zeros to the file (maybe log a warning that it will be slow?).

The option for prealloc is there, and it does not say that it will use zerofill or some other efficient method. Just denying because some type of volume/configuration does not support it seems very user unfriendly to me.

**Comment by lxbsz** [comment]
> I suggest to log the failure of `glfs_zerofill()` and in case it is `ENOTSUP` do a slow write of all zeros to the file (maybe log a warning that it will be slow?).
> 
> The option for prealloc is there, and it does not say that it will use zerofill or some other efficient method. Just denying because some type of volume/configuration does not support it seems very user unfriendly to me.

Yeah, this make sense to me. In tcmu-runner we have already supported something like this, such as for the WRITESAME SCSI command with zeroed data and if the handler doesn't support the zerofill, it will fall back to the slow path by writing one by one.

**Comment by pkalever** [comment]
> I suggest to log the failure of `glfs_zerofill()` and in case it is `ENOTSUP` do a slow write of all zeros to the file (maybe log a warning that it will be slow?).
> 
> The option for prealloc is there, and it does not say that it will use zerofill or some other efficient method. Just denying because some type of volume/configuration does not support it seems very user unfriendly to me.

@nixpanic makesense to me.

@inevity good catch. Do you have plans about sending out a patch for this ?

**Comment by inevity** [comment]
Oh, have leave some days missing those progress.
Will follow your progress. And if some time have ,will patch" the Implement zerofill fop in disperse volumes"

**Comment by lxbsz** [comment]
> Oh, have leave some days missing those progress.
> Will follow your progress. And if some time have ,will patch" the Implement zerofill fop in disperse volumes"

@inevity 
Prasanna have raised one new PR to address it, please see #223.

Thanks.
