### ISSUE TITLE
When replace fails it shouldn't delete the old-node portial

### ISSUE THREAD

**Issue by lxbsz** [gluster/gluster-block#158]
]# gluster-block replace dht/block2 192.168.195.164 192.168.195.160
NAME: block2
CREATE FAILED: 192.168.195.160
DELETE SUCCESS: 192.168.195.164
REPLACE PORTAL SUCCESS ON: N/A
RESULT: FAIL

]# targetcli ls

**Comment by lxbsz** [comment]
@pkalever @amarts 

Will the roll back make sense here if fails happen ?

**Comment by pkalever** [comment]
@lxbsz Can you fix 192.168.195.160 and run sane replace node command again ?
\# gluster-block replace dht/block2 192.168.195.164 192.168.195.160

It should be successful.

**Comment by pkalever** [comment]
I hope it worked for you, if not please open this again later. Thanks!
