### ISSUE TITLE
gluster-blockd refuses to start in openshift pod

### ISSUE THREAD

**Issue by llegolas** [gluster/gluster-block#168]
I'm not sure if this is gluster problem or Redhat image being composed strangely but here is the errors I have in glusterfs-storage pod:
oc rsh -n glusterfs glusterfs-storage-72x7s cat /var/log/glusterfs/gluster-block/gluster-blockd.log|grep ERR
[2018-11-22 08:39:51.310904] ERROR: Distro ID="rhel". Minimum recommended kernel version: '3.10.0-862.11.1' and current kernel version: '3.10.0-862.el7.x86_64'. Hint: Upgrade your kernel and try again. [at gluster-blockd.c+361 :<gbMinKernelVersionCheck>]

If it matters the pod image in question is: 
registry.access.redhat.com/rhgs3/rhgs-server-rhel7      tag:Latest              ImageID:53c83497482a

**Comment by pkalever** [comment]
> This means the kernel version is to low in the node the pod is running, and for the lower kernel there are some bugs that the gluster-block will hit very often.
So what you need to do is to upgrade the kernel to 3.10.0-862.11.1 or higher.

Error will be resoved with kernel-3.10.0-862.11.1, however we recommend kernel version: '3.10.0-862.14.4' which is RHEL 7.5.4 for better experience.

Thanks.

**Comment by lxbsz** [comment]
> > This means the kernel version is to low in the node the pod is running, and for the lower kernel there are some bugs that the gluster-block will hit very often.
> > So what you need to do is to upgrade the kernel to 3.10.0-862.11.1 or higher.
> 
> Error will be resoved with kernel-3.10.0-862.11.1, however we recommend kernel version: '3.10.0-862.14.4' which is RHEL 7.5.4 for better experience.
> 
Yeah, it is.

**Comment by llegolas** [comment]
yeah, 3.10.0-957 also does. I suppose you can close this.

**Comment by pkalever** [comment]
@llegolas that must be RHEL-7.6. Sure, that should be okay.

Closing this issue now. T
