### ISSUE TITLE
Timer base and quick LRU will make sense here ?

### ISSUE THREAD

**Issue by lxbsz** [gluster/gluster-block#192]
@pkalever @amarts 

Currently gluster-block is using the list to host the LRU entries and there is also no timeout, and nbd-runner has support this, please see [1]. 

Will the timer base and LRU make sense in gluster-block project ? If it is okay I will add this in the gluster-block project.

Thanks,

[1] https://github.com/gluster/nbd-runner/pull/64

**Comment by pkalever** [comment]
@lxbsz what problem does this feature solve for us ?

Thanks!

**Comment by lxbsz** [comment]
> @lxbsz what problem does this feature solve for us ?
> 
> Thanks!

Just one enhancement, there is no any issue for the old code.

**Comment by pkalever** [comment]
> Just one enhancement, there is no any issue for the old code.

Exactly! lets not get this now, we can think about this as needed. Thanks for proposing this here.

**Comment by lxbsz** [comment]
That's okay for me :-)
