### ISSUE TITLE
Add logDir dyn support in gluster-block and tcmu-runner

### ISSUE THREAD

**Issue by lxbsz** [gluster/gluster-block#199]
This is missed currently, will add this later.

### Kind of issue
Feature request

### Observed behavior
The log directory path is not configurable through the /etc/sysconfig/gluster-block config file.

### Expected/desired behavior
The logDir is configurable and will change without restarting the gluster-blockd service.

### Details on how to reproduce (minimal and precise)
Currently the dyn config has been support, and we will add dyn-logDir base this.

**Comment by pkalever** [comment]
@lxbsz should we use the ISSUE/FEATURE template, so that it make much sense for others ?

Thanks!

**Comment by lxbsz** [comment]
Make sense and I will check this.
Thanks.
