### ISSUE TITLE
Does gluster-block support to specify lun number?

### ISSUE THREAD

**Issue by phucvinh52** [gluster/gluster-block#20]
Hi everybody,
Does gluster-block support to specify lun id number?
Thanks.

**Comment by pkalever** [comment]
No. As of now it always creates/exports targets with LUN 0.

Any particular reason why we want to mention LUN no. ?

**Comment by pkalever** [comment]
@phucvinh52 we will wait for you response for a week, before we go close this issue.

**Comment by pkalever** [comment]
Closing this issue for now, feel free to open, if the query is not resolved. Thanks!
