### ISSUE TITLE
Upstream Jenkins job which get triggered at PR level

### ISSUE THREAD

**Issue by pkalever** [gluster/gluster-block#219]
### Kind of issue

Infra request:

Need a Jenkins job which should run per PR (and may be more events like, refresh of PR) to help figure out any possible regressions and to help build overall confidence of upstream master branch.

### Other useful information

To start with, we can build like we do with [travis](https://github.com/gluster/gluster-block/blob/master/extras/docker/Dockerfile.fedora29)

Need to install run time dependencies:
\# yum install glusterfs-server targetcli tcmu-runner

then start glusterd
\# systemctl start glusterd

Then run simple test case
\# [./tests/basic.t](https://github.com/gluster/gluster-block/blob/master/tests/basic.t)

**Comment by deepshikhaaa** [comment]
Where we will be running these regressions?
centos.ci?

**Comment by pkalever** [comment]
> Where we will be running these regressions?
> centos.ci?

@deepshikhaaa where do we run the jenkins job to for regression tests for glusterfs ? centos.ci ?

I would love to see one running on fedora, as most of kernel and user land packages appears there first.
But I'm not sure if we have machines to runs the job on fedora instances.

@amarts thoughts ?

**Comment by deepshikhaaa** [comment]
No, we do run glusterfs regression jobs on our jenkins server. I'm asking this because we do have running few gluster-block jobs on centosci.

**Comment by pkalever** [comment]
> No, we do run glusterfs regression jobs on our jenkins server. I'm asking this because we do have running few gluster-block jobs on centosci.

How frequently these gluster-block jobs in centosci run ? can you share the link here, we are not aware about this ?

@deepshikhaaa if we are running glusterfs regression jobs on our jenkins server, can we share the same with gluster-block ?

Thanks!

**Comment by sankarshanmukhopadhyay** [comment]
There is quite a mix of things here and also, ideally this should be a RHBZ on the project-infrastructure component (I'm not exactly sure, but it seems that way)

- it would likely to be more efficient to have this set up to consume the CentOS CI infrastructure
- I do not recollect whether we have existing jobs against a Fedora target. I see the value and rationale for this specific component. But, it may have to be of secondary priority - we kick the tires with CentOS target and then add more jobs

**Comment by pkalever** [comment]
@deepshikhaaa do we have any progress on this?

**Comment by pkalever** [comment]
Won't Fix, closing now.
