### ISSUE TITLE
Setup GCOV & LCOV job

### ISSUE THREAD

**Issue by pkalever** [gluster/gluster-block#220]
### Kind of issue

Infra request:

Setup GCOV & LCOV job which should run nightly or weekly to help visualize test & line coverage achieved, which intern help us understand:

* how often each line of code executes
* what lines of code are actually executed
* how much computing time each section of code uses

and work on possible optimizations.

### Other useful information

To start with, we can build like we do with [travis](https://github.com/gluster/gluster-block/blob/master/extras/docker/Dockerfile.fedora29)

Need to install run time dependencies:
\# yum install glusterfs-server targetcli tcmu-runner

then start glusterd
\# systemctl start glusterd

Then run simple test case
\# [./tests/basic.t](https://github.com/gluster/gluster-block/blob/master/tests/basic.t)

**Comment by sankarshanmukhopadhyay** [comment]
Seems like a RHBZ on project-infrastructure that is needed. To confirm, you expect a listing similar to https://build.gluster.org/job/line-coverage/Line_20Coverage_20Report/

**Comment by pkalever** [comment]
> Seems like a RHBZ on project-infrastructure that is needed. To confirm, you expect a listing similar to https://build.gluster.org/job/line-coverage/Line_20Coverage_20Report/

Yes, this is the expectation.
Here is the bug: https://bugzilla.redhat.com/show_bug.cgi?id=1703433

Thanks!

**Comment by pkalever** [comment]
We have https://ci.centos.org/view/Gluster/job/gluster_block-lcov/

Thanks @deepshikhaaa
