### ISSUE TITLE
Improve output of gluster-block info

### ISSUE THREAD

**Issue by vbellur** [gluster/gluster-block#23]
Sample output of gluster-block info is as below:

> gluster-block info rep/bd1
> NAME: bd1
> VOLUME: rep
> GBID: 4ddce603-c1cc-496e-a0ba-d4f537c26422
> SIZE: 53687091200
> HA: 3
> PASSWORD: 
> BLOCK CONFIG NODE(S): 10.16.154.60 10.16.154.45 10.16.154.63

Some suggested improvements:

1. Displaying the size value in the unit it was configured (50 GiB in this case) or in a more human readable way would be nice. 

2. BLOCK CONFIG NODE(S) does not seem very intuitive. A better string like "Exported Node(S)" or something else might make it more intuitive.

**Comment by pkalever** [comment]
Patch available:
https://review.gluster.org/#/c/17519/
