### ISSUE TITLE
logo for gluster-block ?

### ISSUE THREAD

**Issue by pkalever** [gluster/gluster-block#236]
![gluster-block-logo](https://user-images.githubusercontent.com/12432241/57435437-0b60e280-725b-11e9-8534-80217f7deee8.png)

This would be my proposal, feel free to propose your :-)

Lets sort this out in a week or so.

**Comment by lxbsz** [comment]
@pkalever 

Cool and the blocks are very vivid here for the gluster-block project.
This looks nice to me.

Thanks.

**Comment by pkalever** [comment]
> @pkalever
> 
> Cool and the blocks are very vivid here for the gluster-block project.
> This looks nice to me.

@lxbsz its not that simple to skip so easily.  I'm expecting one from you too :-)

I know, its out of our expertise, but believe me, it's gonna be lots of fun, let's be sportive here and append our logo of choice to this page.

Cheers!

**Comment by lxbsz** [comment]
> 
> @lxbsz its not that simple to skip so easily. I'm expecting one from you too :-)
> 
> I know, its out of our expertise, but believe me, it's gonna be lots of fun, let's be sportive here and append our logo of choice to this page.
> 
@pkalever 

Yeah, true. I am not good at this :-(
And I will have a try if I can get one.

Thanks.
BRs

> Cheers!

**Comment by nixpanic** [comment]
Maybe @tigert has an idea?
