### ISSUE TITLE
Get gluster-block accepted as package in Fedora

### ISSUE THREAD

**Issue by nixpanic** [gluster/gluster-block#25]
The process to become an official Fedora Packager is described on the [Package Maintainers](https://fedoraproject.org/wiki/Category:Package_Maintainers) wiki page.

I should be able to help out in case assistance or further explanations are needed. However the people in `#fedora-devel` on Freenode are normally quite responsive too.

**Comment by nixpanic** [comment]
Started the [Package Review Process](https://fedoraproject.org/wiki/Package_Review_Process). The request has been filed as [Review Request: gluster-block - A framework for gluster block storage management](https://bugzilla.redhat.com/show_bug.cgi?id=1467677)

**Comment by pkalever** [comment]
Fedora package for gluster-block available now. Thanks @nixpanic
