### ISSUE TITLE
The RINGBUFFER and BLOCKSIZE in metafile are missed

### ISSUE THREAD

**Issue by lxbsz** [gluster/gluster-block#257]
### Kind of issue
Feature request

### Observed behavior
There is no any thing about the RINGBUFFER and BLOCKSIZE in the meta file.

### Expected/desired behavior
If user has specify them we should see them in the meta or the gluster-block info.

**Comment by pkalever** [comment]
@lxbsz can we close this, please?

**Comment by lxbsz** [comment]
Sure, will close it.
