### ISSUE TITLE
gluster-block uninstallable on Fedora 31 from dnf

### ISSUE THREAD

**Issue by bluecmd** [gluster/gluster-block#260]
Using a clean Fedora 31 at 2019-12-10:

```
[bluecmd@iscsi2 ~]$ sudo dnf install gluster-block
Last metadata expiration check: 0:00:39 ago on Tue 10 Dec 2019 10:19:05 PM CET.
Error: 
 Problem: conflicting requests
  - nothing provides python-rtslib >= 2.1.fb69 needed by gluster-block-0.4-4.fc31.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by bluecmd** [comment]
Seems that for rtslib it's fine to just replace with `python3-rtslib` as python is symlinked to python3. But for configshell the python3-configshell package is too old for this to work (complains of lacking __version__ e.g.).

**Comment by lxbsz** [comment]
Not test the gluster-block in f31 yet. You may could build and install all of them from the source.

**Comment by pkalever** [comment]
@bluecmd we are currently working on this https://bugzilla.redhat.com/show_bug.cgi?id=1830514

Meanwhile you can download the rpms from https://koji.fedoraproject.org/koji/packageinfo?packageID=24885

**Comment by pkalever** [comment]
Closing now.
