### ISSUE TITLE
Centos8 - ImportError: cannot import name '__version__'

### ISSUE THREAD

**Issue by lenhardtx** [gluster/gluster-block#262]
### Kind of issue

> Uncomment only one of these:
>
Bug
> Feature request

### Observed behavior
Jan 04 02:45:35 glusterfs.localdomain gluster-blockd[6717]: Traceback (most recent call last):
Jan 04 02:45:35 glusterfs.localdomain gluster-blockd[6717]:   File "<string>", line 1, in <module>
Jan 04 02:45:35 glusterfs.localdomain gluster-blockd[6717]: ImportError: cannot import name '__version__'

### Expected/desired behavior
systemctl start gluster-blockd

### Details on how to reproduce (minimal and precise)
packages provided according to the documentation

### Logs and Information about the environment:

glusterfs 7.1 ( https://download.gluster.org/pub/gluster/glusterfs/LATEST/CentOS/el-8.1/x86_64/ )
gluster-block 0.4 

python3-gluster-7.1-1.el8.x86_64
tcmu-runner-1.5.2.17.g020f8e9-0.el8.x86_64
glusterfs-7.1-1.el8.x86_64
glusterfs-cli-7.1-1.el8.x86_64
glusterfs-server-7.1-1.el8.x86_64
glusterfs-libs-7.1-1.el8.x86_64
glusterfs-client-xlators-7.1-1.el8.x86_64
glusterfs-api-7.1-1.el8.x86_64
glusterfs-fuse-7.1-1.el8.x86_64
glusterfs-extra-xlators-7.1-1.el8.x86_64
libtcmu-1.5.2.17.g020f8e9-0.el8.x86_64
libtcmu-devel-1.5.2.17.g020f8e9-0.el8.x86_64
python3-rtslib-2.1.fb69-3.el8.noarch
targetcli-2.1.fb49-1.el8.noarch
glusterfs-devel-7.1-1.el8.x86_64
glusterfs-api-devel-7.1-1.el8.x86_64

- logs:
  - from all target/server nodes:
    - /var/log/gluster-block/ directory
    - /etc/target/saveconfig.json file
    - $ targetcli ls
  - from initiator node: (only needed if the issue is from client side)
    - $ multipath -ll
    - $ lsblk
    - /etc/multipath.conf file

**Comment by pkalever** [comment]
@lenhardtx

Patch 1:

```
commit 6ee4c6756a7f41ef9c1d7b0ad594a78b4b45929f
Author: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>
Date:   Wed Jul 3 15:32:21 2019 +0530

    rtslib: fix __version__
```

Is part of rtslib version 2.1.70



and

Patch 2:

```
commit 097982d3484f30e32dc03113944186f471f36505
Author: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>
Date:   Wed Jul 3 15:47:18 2019 +0530

    configshell: export __version__ variable
```

Is part of configshell version 1.1.26


IMO, the issue that you are facing will be fixed by Patch 2 above in configshell, but it will be nice to have Patch 1 as well.

Please upgrade your targetcli/rtslib/configshell dependencies to latest masters, that should solve it for you.

**Comment by lenhardtx** [comment]
update configshell fix the problem as you said. Thank you.
