### ISSUE TITLE
Trouble formatting Gluster Block

### ISSUE THREAD

**Issue by cnewtonEncompass** [gluster/gluster-block#276]
After following all the instructions at https://pkalever.wordpress.com/2019/05/06/starting-with-gluster-block/, I run into an error when running the mkfs.xfs formatting (also tried mxfs.ext4)

I have a feeling this is something really simple but cannot find any information on the web about it.
[root@atl-gluster-04 glusterfs]# mkfs.xfs /dev/sds
meta-data=/dev/sds               isize=512    agcount=4, agsize=3276800 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=1        finobt=0, sparse=0
data     =                       bsize=4096   blocks=13107200, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
log      =internal log           bsize=4096   blocks=6400, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
mkfs.xfs: pwrite64 failed: Input/output error
[root@atl-gluster-04 glusterfs]# 

Logs show lots of scsi errors
[24936.039953] blk_update_request: I/O error, dev sds, sector 122
[24936.040451] sd 13:0:0:0: [sds] FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[24936.040458] sd 13:0:0:0: [sds] Sense Key : Medium Error [current] 
[24936.040464] sd 13:0:0:0: [sds] Add. Sense: Write error
[24936.040469] sd 13:0:0:0: [sds] CDB: Write(10) 2a 00 00 00 00 00 00 00 7a 00
[24936.040474] blk_update_request: I/O error, dev sds, sector 0

Any help anyone can give me would be most appreciated.

**Comment by lxbsz** [comment]
Hi @cnewtonEncompass 

Do you have any target side dmesg and tcmu-runner/tcmu-runner-glfs logs ?

[24936.040458] sd 13:0:0:0: [sds] Sense Key : Medium Error [current] 

It seems there has some stories in the backend ...

**Comment by pkalever** [comment]
Closing this now.
