### ISSUE TITLE
just support create block on replica volume?

### ISSUE THREAD

**Issue by perrynzhou** [gluster/gluster-block#283]
## @pranithk @pkalever  gluster-block service just support create block service on replica volume?when i create block on distribute volume,that is failed

**Comment by pkalever** [comment]
@perrynzhou 

Yes, we recommend glusterfs volume with replica 3 and group profile gluster-block applied.

```
# gluster volume create myglustervol replica 3 NODE1:/brick1 NODE2:/brick2 NODE3:/brick3 force
# gluster vol set myglustervol group gluster-block
# gluster vol start myglustervol
```

**Comment by perrynzhou** [comment]
@pkalever  is any plan to support create block on distribute volume? that match to glusterfs service.

**Comment by pkalever** [comment]
Not really, it needs much more testing efforts.

**Comment by perrynzhou** [comment]
@pkalever  i think that should support all types of volume ,such distribute volume/ec volume/replica volume

**Comment by pkalever** [comment]
The project is considered to be in maintenance-only status. I will consider adding this in the ReadMe doc soon. Hence I think supporting it is not possible.

Thanks!
