### ISSUE TITLE
gluster-block is not update and maintain?

### ISSUE THREAD

**Issue by perrynzhou** [gluster/gluster-block#285]
gluster-block project already not update for long time.that means not update at all?or not maintain glsuter-block at all?

**Comment by jonahbohlmann** [comment]
Good question. What is about this project?

**Comment by pkalever** [comment]
the project is considered to be in maintenance-only status. I will consider adding this in the ReadMe doc soon.

**Comment by pkalever** [comment]
We have added the details to the readme now, closing this. Thanks!
