### ISSUE TITLE
gluster-block create prints "(null)" when tcmu-runner is not running

### ISSUE THREAD

**Issue by pranithk** [gluster/gluster-block#31]
11:18:28 :( ⚡ gluster-block create d1/1-img ha 1 localhost.localdomain 10GiB
(null)
RESULT:FAIL

This happens when tcmu-runner is not running. Sent https://review.gluster.org/17622 to fix it and it prints:
11:45:18 :( ⚡ gluster-block create d1/1-img ha 1 localhost.localdomain 10GiB
failed to configure on localhost.localdomain tcmu-runner not running
RESULT:FAIL

**Comment by pkalever** [comment]
Fixed https://review.gluster.org/#/c/17622/
