### ISSUE TITLE
Modify succeeds even when tcmu-runner is not running

### ISSUE THREAD

**Issue by pranithk** [gluster/gluster-block#34]
root@dhcp35-190 - ~ 
22:04:52 :( ⚡ gluster-block create r3/1-img ha 1 192.168.122.1 1GiB
IQN: iqn.2016-12.org.gluster-block:799008ab-4bf5-46f7-b2ed-c04320aae32c
PORTAL(S):  192.168.122.1:3260
RESULT: SUCCESS

Bring tcmu-runner down on the node where the block is configured. After that:
root@dhcp35-190 - ~ 
22:05:50 :) ⚡ gluster-block delete r3/1-img
tcmu-runner is not running in few nodes
RESULT:FAIL

This marks the block as CLEANUPINPROGRESS so next commands won't consider this node for execution, because of this:
root@dhcp35-190 - ~ 
22:06:45 :( ⚡ gluster-block modify r3/1-img auth enable
IQN: iqn.2016-12.org.gluster-block:799008ab-4bf5-46f7-b2ed-c04320aae32c
USERNAME: 799008ab-4bf5-46f7-b2ed-c04320aae32c
PASSWORD: 1490c6ec-8519-4a53-8524-037781f941c8
RESULT: SUCCESS

**Comment by pkalever** [comment]
@lxbsz please feel free to take a look. Looks like I cannot assign you some old issues.

**Comment by pkalever** [comment]
@pranithk this might be because we are returning 0, even if target is not loaded ?

**Comment by pkalever** [comment]
Works for me.
