### ISSUE TITLE
Use environment file instead of variables 

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [gluster/gluster-block#36]
We have these files :
systemd file
https://github.com/gluster/gluster-block/blob/master/systemd/gluster-blockd.service.in

environment file
https://github.com/gluster/gluster-block/blob/master/systemd/gluster-blockd.sysconfig

We have all variables commented inside env. file above.
It is better to uncomment all these variables and remove all variables from systemd file above.

**Comment by pkalever** [comment]
Please reopen this issue, if you feel this is not fixed yet.
