### ISSUE TITLE
Windows cant use block device

### ISSUE THREAD

**Issue by Oliver-Chang** [gluster/gluster-block#38]

**Comment by YUNZHONGTAN** [comment]
windows 10 can support it

**Comment by pkalever** [comment]
@Oliver-Chang do you still face the problem ?

**Comment by pkalever** [comment]
@Oliver-Chang ping!
Do you still face the problem ?

**Comment by poxin13** [comment]
I'm able to mount a block device in windows and get it setup using initiator, though I don't think it's using multipath. Under discovery -> target portals each IP is added of the block device. In the linux tutorials it seems only one IP is needed and the rest are discovered. Anyone have insight how to get that part working in windows?

**Comment by pkalever** [comment]
Closing this now. Feel free to open.
