### ISSUE TITLE
Support for snapshots

### ISSUE THREAD

**Issue by nixpanic** [gluster/gluster-block#42]
It would be great if the gluster-block CLI can provide support for snapshots. A naive implementation can create a (full) copy of the file that is used by tcmu-runner. The minimal usable functionality should support the following commands:

- `create-snapshot [--tag=<TAG>] <VOLNAME/BLOCKNAME>`: create a copy of the `<VOLNAME/BLOCKNAME>` file with the optional user provided `<TAG>` added to the xattrs of the copy (the filename of the snapshot should probably be appended with a UUID for identification)
- `list-snapshots <VOLNAME/BLOCKNAME>`: show all snapshots that are available for the `<VOLNAME/BLOCKNAME>`, and list UUID, creation date and `<TAG>`
- `restore-snapshot <VOLNAME/BLOCKNAME> <UUID>`: deletes/renames the current `<VOLUME/BLOCKNAME>` and copies the snapshot back to `<VOLNAME/BLOCKNAME>`
- `delete-snapshot <VOLNAME/BLOCKNAME> <UUID>`: deletes the snapshot

This requires `gluster-blockd` to flush+freeze access to the `<VOLNAME/BLOCKNAME>` (similar to `fsfreeze`) while snapshot operations are in progress. This functionality might need to be implemented in `targetcli` and `tcmu-runner`.

Future versions of Gluster may offer more efficient methods for storing snapshots of files (reflink?), but the majority of the required functionality will stay the same for most of the other involved components.

**Comment by pranithk** [comment]
Based on https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/volume-snapshotting.md, it looks like the storage doesn't need to worry about fs-consistency, it is something kube will do.

**Comment by nixpanic** [comment]
Indeed, it is expected that the user/operator initates a snapshot
workflow that ideally includes

- informing the application to flush its caches and pause coming writes
- call fsfreeze on the filesystem that gets snapshot'ed
- gluster-block does the snapshot
- unfreeze the filesystem
- inform the application that writes can be done again

The 1st and last step may not be possible with all applications or
environments and is sort-of optional. Applications should be able to
recover of partial writes when data is not synced to the filesystem or
block device.

**Comment by pkalever** [comment]
Won't Fix, closing now.
