### ISSUE TITLE
iscsi, targetcli and VAAI

### ISSUE THREAD

**Issue by hetzbh** [gluster/gluster-block#46]
Since gluster-block uses the targetcli "infrastructure", can I use the targetcli VAAI functions for VMware acceleration? (See this link for more info: https://goo.gl/dLUPsV )

**Comment by lxbsz** [comment]
Since the tcmu-runner has already adding the VAAI emulator support . Though the glfs hasn't to do the local VAAI supporting, it will fallback to use the emulator methods.

I think it should be okay.

**Comment by pkalever** [comment]
@hetzbh does @lxbsz comment help ?
