### ISSUE TITLE
The best way to allow max block to be settable

### ISSUE THREAD

**Issue by lxbsz** [gluster/gluster-block#47]
@pkalever @pranithk @vbellur @all

As we discussed last meeting, if we will allow the max block to be settable for each target device. Which is the best way to do ?

1,  intergrated into create command:

  commands:
  create  <volname/blockname> [ha <count>]
                              [auth <enable|disable>]
                              [prealloc <full|no>]
                              [storage <filename>]
                              <host1[,host2,...]> <size>
                              **_[rb_size \<size\>]_**
        create block device [defaults: ha 1, auth disable, prealloc no, size in bytes, **_rb_size as default in kernel]_**

2, In the config file as a parameter.

NOTE: currently the default RingBuffer size for data block is 8M, and the max settable is 64M for each target device.

Thanks,

**Comment by lxbsz** [comment]
https://review.gluster.org/#/c/19680/

**Comment by pkalever** [comment]
Fixed by https://github.com/gluster/gluster-block/pull/64
