### ISSUE TITLE
No caching at the client side

### ISSUE THREAD

**Issue by pkalever** [gluster/gluster-block#67]
Because the client ungraceful shutdown could lead us to file-system corruption

**Comment by pkalever** [comment]
@lxbsz  @vbellur @pranithk thoughts ?

**Comment by lxbsz** [comment]
@pkalever Is this related to the XFS corruption issue ?

**Comment by pkalever** [comment]
@lxbsz yes it is.

**Comment by pranithk** [comment]
@pkalever Ungraceful shutdown leads to problems even on disk filesystems. Removing caching to handle ungraceful shutdowns is punishing who do graceful shutdowns. Better would be to prevent ungraceful shutdown instead.

**Comment by pkalever** [comment]
So in that case one should always make sure to unmount the device before the shutdown.

Request to comment: @obnoxxx @raghavendra-talur @humblec @nixpanic

**Comment by lxbsz** [comment]
@pkalever @pranithk While ungraceful shutdown couldn't be prevent for some reason, such as the system crash. And agree with pranithk closing the cache is punishing to the normal case.

**Comment by pranithk** [comment]
> So in that case one should always make sure to unmount the device before the shutdown.

> Request to comment: @obnoxxx @raghavendra-talur @humblec @nixpanic

Yes, that is how all the disk filesystems work. We need to understand why ungraceful shutdown is the norm and fix it.

**Comment by nixpanic** [comment]
The order of shutdown is important in this case. It probably should be this:

1. stop pods using gluster-block provided filesystems
2. unmount the iscsi backed filesystems (flushes data to the block devices, iscsi should flush too)
3. stop gluster-block/tcmu-runner (flush data received over iscsi to Gluster)
4. stop the Gluster pods
5. unmount filesystems used by the Gluster pods
6. reboot

If the order is different, there could be timeouts that prevent flushing the data at one point (multipath-failover, gfapi/afr ping timeout, ..).

I do not know what special precautions are taken to do a correct shutdown/reboot.

**Comment by pkalever** [comment]
Won't Fix, closing now.
