### ISSUE TITLE
Block creation fails

### ISSUE THREAD

**Issue by ams0** [gluster/gluster-block#74]
I want to setup a standalone 3-node cluster exporting two gluster volumes via iSCSI (mounted with multipath by multiple clients). I have Gluster 3.8 and gluster-block 0.3; I have two healthy volumes over 3 nodes with RHEL7.4 and targetcli version 2.1.fb46 (g1b, g2b and g3b):

```
[root@g3 gluster-block]# gluster vol status
Status of volume: db2data
Gluster process                             TCP Port  RDMA Port  Online  Pid
------------------------------------------------------------------------------
Brick g1b:/bricks/db2data/db2data           49152     0          Y       23649
Brick g2b:/bricks/db2data/db2data           49152     0          Y       23619
Brick g3b:/bricks/db2data/db2data           49152     0          Y       23563
Self-heal Daemon on localhost               N/A       N/A        Y       23625
Self-heal Daemon on g1b                     N/A       N/A        Y       23716
Self-heal Daemon on g2b                     N/A       N/A        Y       23684
Task Status of Volume db2data
------------------------------------------------------------------------------
There are no active volume tasks
Status of volume: db2quorum
Gluster process                             TCP Port  RDMA Port  Online  Pid
------------------------------------------------------------------------------
Brick g1b:/bricks/db2quorum/db2quorum       49153     0          Y       23696
Brick g2b:/bricks/db2quorum/db2quorum       49153     0          Y       23661
Brick g3b:/bricks/db2quorum/db2quorum       49153     0          Y       23605
Self-heal Daemon on localhost               N/A       N/A        Y       23625
Self-heal Daemon on g1b                     N/A       N/A        Y       23716
Self-heal Daemon on g2b                     N/A       N/A        Y       23684
Task Status of Volume db2quorum
------------------------------------------------------------------------------
There are no active volume tasks
```
Volume mounts locally fine (on _/db2/data/data_ and _/db2/quorum_). When I want to create a block device with:

```
gluster-block create db2data/data1 ha 3 g1b,g2b,g3b 40GiB
```
The device is created and then destroyed immediately, targetcli commands are visible in the logs:

[gluster-blockd.log ](https://paste.fedoraproject.org/paste/TZ28mp4Lk2T3fV1bET2E2Q)
[gluster-block-gfapi.log ](https://paste.fedoraproject.org/paste/7xt9vM10bjaDTqlUGmksHg)

I can create manually a file and use it as a LUN:

```
[root@g1 rhel]# fallocate -l 10G /db2/data/data
[root@g1 rhel]# targetcli /backstores/user:glfs create glfsLUN 10G db2data@g1b/data
Created user-backed storage object glfsLUN size 10737418240.
```

I'm a bit lost on the root cause and I'm very new to gluster-block. Any help appreciated.

**Comment by ams0** [comment]
g{1-3} are all VM's in Azure in the same vnet and region, firewall is off, and the network security group allows 111,3260(tcp),49152-49160(tcp),24007-24010(tcp).

**Comment by pkalever** [comment]
@ams0 Please use the Host IP addresses instead of g1b,g2b,g3b

i.e. something like,
$ gluster-block create db2data/data1 ha 3  192.168.124.1,192.168.124.2,192.168.124.3 40GiB

I feel gluster-block should return a valid error/user msg when hostnames are supplied instead of IP addr's (atleast until it supports hostnames)

Thanks!

**Comment by ams0** [comment]
hi

thanks! In hindsight, I should have tried right away - it worked immediately:

```
[root@g3 data]# gluster-block create db2data/GFS ha 3 192.168.2.10,192.168.2.11,192.168.2.12 40GiB
IQN: iqn.2016-12.org.gluster-block:5657f145-cdb9-4764-8a24-95f055191a2c
PORTAL(S):  192.168.2.10:3260 192.168.2.11:3260 192.168.2.12:3260
RESULT: SUCCESS
[root@g3 data]#
```

Indeed, it does work, but docs are a bit obscure and I could have definitely a bit more verbose error description. Also, why it doesn't work with hostnames? Is it an iSCSI thing or gluster-block limitation?

Thanks anyhow! I

**Comment by ams0** [comment]
I wrote a small post on it: https://medium.com/cooking-with-azure/multipath-iscsi-in-azure-with-glusterfs-and-gluster-block-on-rhel-f64e5f7a9ec3 , thanks @pkalever , I can close this.

**Comment by pkalever** [comment]
Hi @ams0,

Nice Article, Thumbs up!!

I will add defense code for host-name's in the gluster-block soon.
The hostnames issue is something that I raised more than a year ago now, see [1]
I will have to try debug that myself and fix if possible someday soon.

[1] https://lists.fedorahosted.org/archives/list/targetcli-fb-devel@lists.fedorahosted.org/thread/4E5XQQREDX6S742GRXM7GOLPAEJZQYVX/


Thanks!
