### ISSUE TITLE
Use correct gfapi function signatures

### ISSUE THREAD

**Issue by bhumikagoyal** [gluster/gluster-block#75]
This issue came up while installing gluster-block on top of glusterfs 4.1dev. 
The gfapi functions have changed as per the discussion https://github.com/gluster/glusterfs/issues/389# but some gfapi calls inside gluster-block are not updated and are still using the old apis. 
Therefore, update the below functions to use the changed gfapi.

- [ ] glfs_ftruncate

**Comment by amarts** [comment]
#77 should have made a reference here!

**Comment by pkalever** [comment]
Fixed by: https://github.com/gluster/gluster-block/pull/178
