### ISSUE TITLE
How to use gluster-block to operate gluster-blockd on remote machine?

### ISSUE THREAD

**Issue by singhwang** [gluster/gluster-block#79]
I want to use gluster-block utility to operate gluster-blockd process on remote machines. How can I configure it, please?

**Comment by pkalever** [comment]
Please go through [ReadMe](https://github.com/gluster/gluster-block/blob/master/README.md)  file.

If you have any queries after that, you can post them here.

Thanks!

**Comment by pkalever** [comment]
@singhwang ping. ^^

**Comment by amarts** [comment]
@singhwang closing as there is no update on this! Feel free to reopen if it doesn't answer the question.
