### ISSUE TITLE
Unable to format LUN 

### ISSUE THREAD

**Issue by BlackoutWNCT** [gluster/gluster-block#84]
So, I'm not sure if this is user error, or which component of this solution is currently causing these issues, but I'm having trouble formatting the exposed objects.
The below paste is a section of journalctl on the initiator which was attempting to format and mount the LUN.
There is also a paste of the `targetcli ls` at the bottom.

https://paste.ubuntu.com/p/TPpTZmgwJP/

These errors occured using the following packages:

Target:
- CentOS 7
- Gluster 4.0
- TCMU-Runner 1.3
- Gluster-Block 0.3
(The packages used were all included in the `centos-release-gluster40.x86_64` repo)

Initiator:
- Fedora 25
- iSCSIadm

- Windows Server 2016

I've also tried this same setup using gluster 3.12 and compiling both the gluster-block and tcmu-runner packages from git. I get the same result.

If there is instead a specific set of package versions I should be using, please let me know.

I'm not 100% this is a gluser-block issue, and so I'll also be raising an issue on the tcmu-runner git.

If any additional info is needed, please let me know.

**Comment by lxbsz** [comment]
@BlackoutWNCT 
Thanks for your reporting about this.

>   | o- user:glfs .............................................................................................. [Storage Objects: 1]
>   | | o- TestLUN01 ...................... [GVTest@10.1.100.111/block-store/c469322d-d6b2-4cae-b555-35fff90f575c (10.0GiB) activated]
>   | |   o- alua ................................................................................................... [ALUA Groups: 0]

As default, there should be one default alua tpg, like:

>   | o- user:glfs .............................................................................................. [Storage Objects: 2]
>   | | o- block0 ......................... [dht1@192.168.195.159/block-store/0f51931a-6889-4253-9a63-76d31fe8654e (1.0KiB) activated]
>   | | | o- alua ................................................................................................... [ALUA Groups: 1]
>   | | |   o- default_tg_pt_gp ....................................................................... [ALUA state: Active/optimized]

Not sure will it have some affect about this.

Currently I didn't have the CentOS setups. And the logs you pasted are from initiator side, I couldn't be sure what's the root cause from this logs.

Could you upload the following logs from the target side ?
1, /var/log/gluster-block/*
2, /var/log/glusterfs/*
3, /var/log/messages
4, journalctl  > journalctl.log

And please upload all the log files from the 3 target nodes.

Thanks,

**Comment by pkalever** [comment]
@BlackoutWNCT could we get the requested information ?

Thanks!

**Comment by pkalever** [comment]
@BlackoutWNCT ping!

**Comment by BlackoutWNCT** [comment]
You guys asked me to upload logs for something 3 months after it had been reported.
Those logs no longer exist.
I also no longer work for that company, and so am no longer able to investigate this issue.
Please just close this issue.

**Comment by pkalever** [comment]
@BlackoutWNCT sorry for the delay! Somehow this got lost.

You should Feel free to ping back when you don't get a reply in a week or so.

Anyways, what was the usecase ? at-least this will help us improve our regression tests in that direction. 

Thanks!

**Comment by BlackoutWNCT** [comment]
My end goal with this was to use glusterblock to expose a number of iSCSI LUNs to a Windows Server 2012/2016 Hyper-V cluster for use in a HA DR cluster.

**Comment by pkalever** [comment]
Appreciate you response.
Thanks for sharing your usecase with us.
