### ISSUE TITLE
single login per target

### ISSUE THREAD

**Issue by pkalever** [gluster/gluster-block#9]
Currently from the initiator side we need to login to mpath number of node to get multipathed block devices at the client side. This can be minimized to single login per target by configuring all gateways for a particular target in all gateways.

**Comment by pkalever** [comment]
Adding to the above justification,

This feature should help in managing load balancing ...
Yes!

Currently,
$ gluster-block create VOL/BLOCK ha 3 HOSTx,HOSTy,HOSTz
Creates only one TPG i.e tpg1 (Read as Target Portal Group with Tag 1) on each node, with one portal listening on respective IP. All the gateways/nodes emulate same backend as target LUN with same WWN (for multipath representation)

So we login to individual nodes (Thrice) 
# iscsiadm -m discovery -t st -p HOSTy -l
# iscsiadm -m discovery -t st -p HOSTz -l
# iscsiadm -m discovery -t st -p HOSTx -l

In the above case, user may login in any fashion, which is out of our control. Since we have failover multipath configuration, at a given time only one gateway can TX RX the data. so predicting active connection is not possible.


With this feature,
$ gluster-block create VOL/BLOCK ha 3 HOSTx,HOSTy,HOSTz
Creates 3 TPG's, tpg1(portal HOSTx), tpg2(portal HOSTy), tpg3(portal HOSTz) on all the three gateways/nodes ( IN same Order).

Basically, each gateway is define to every other gateway - but the other gateway entries are in a disabled state. When the client starts the login sequence it issues the RPTG to the one nodes, but now that node can respond with portal IP's for all of the gateways.

e.g.
GW1                                      GW2                                   GW3
-tpg1/enabled                        - tpg1/disabled                    - tpg1/disabled
- tpg2/disabled                      - tpg2/enabled                     - tpg2/disabled
- tpg3/disabled                      - tpg3/disabled                     - tpg3/enabled

Advantage,
1. Only one login is needed, unlike 3 login's before.
    $ iscsiadm -m discovery -t st -p ANYONEHOST -l

2. Always tpg1 will be tried for making an active connection, hence we can predict that the first host in the list {HOSTx,HOSTy,HOSTz} will be tried for active connection. Hence we can be able to better manage load on each nodes, by selectively supplying Hosts in the list.

Please reconsider the importance of this feature. @vbellur @pranithk @nixpanic

**Comment by nixpanic** [comment]
A single login is surely useful, but does it still allow to use device-mapper-multipath? If there is a single login, does it not have a single `/dev/sd*` device too?

**Comment by pkalever** [comment]
@nixpanic :-) We still have the multipathed devices, same as old.

From my above example, all of sda, sdb, sdc i.e. 3 devices will be mapped and considered to be one device (may be mpatha) with multiple paths to target device.

**Comment by nixpanic** [comment]
Ok, it looks like a great usability improvement then!

**Comment by nixpanic** [comment]
One this is not very clear to me though... If only one TPG is enabled at the time, what makes failover happen to an other TPG? Is that handled by a dm-multipath policy automatically, or is that something that needs to be triggered on the TPGs themselves?

**Comment by pkalever** [comment]
The disabled TPG's in each gateways are just to help in discovery of all the portals tied for that target.
But the actual connection happens with the individual gateways where there are enabled tpg's.

Example:
lets consider NODE1, NODE2 & NODE3
On each of these NODE we have 3 tpg's each. Again each of the tpg has different portal.

**NODE1**/GW1
tpg1
  -- portal: NODE1_IP:3260 -- **enabled**
tpg2
  -- portal: NODE2_IP:3260 -- disabled
tpg3
  -- portal: NODE3_IP:3260 -- disabled

**NODE2**/GW2
tpg1
  -- portal: NODE1_IP:3260 -- disabled
tpg2
  -- portal: NODE2_IP:3260 -- **enabled**
tpg3
  -- portal: NODE3_IP:3260 -- disabled

**NODE3**/GW3
tpg1
  -- portal: NODE1_IP:3260 -- disabled
tpg2
  -- portal: NODE2_IP:3260 -- disabled
tpg3
  -- portal: NODE3_IP:3260 -- **enabled**


Note: only one tpg (with local IP as portal) will be enabled on that node.
This mechanism will help in discovering all the portals belonging to that target.

Point to be noted, While Login the Nexus will be established only between the real gateway.
sda --- Initiator and NODE1
sdb --- Initiator and NODE2
sdc --- Initiator and NODE3

Lets say in our failover multipath config sda is active, in case if NODE1 goes down dm_mpath will help in switching to tpg2's portal which will be NODE2 automatically.

**Comment by pkalever** [comment]
Available for review:  https://review.gluster.org/#/c/17069/
please-review: @vbellur @pranithk @nixpanic
