### ISSUE TITLE
saveconfig.json reset after reboot & gluster-blockd start

### ISSUE THREAD

**Issue by softyn** [gluster/gluster-block#95]
I have following problem - I am getting configuration reset after rebooting server(s).

I have 2 servers with gluster and gluster block (v0.3) installed.
Steps to reproduce problem:
1. Create any volume e.g
gluster-block create test/fortest ha 2 192.168.1.15,192.168.1.16 1GiB
2. I can see that it is working e.g. opening targetcli on both machines
 I can restart gluster-blockd or tcmu-runner  and still have proper data in saveconfig.json
3. When I restart one of servers (without auto-start of tcmu-runner and gluster-blockd) . I can see that targetcli still has correct created previously data.
4. I run tcmu-runner 
5. But after starting gluster-blockd  my file /etc/target/saveconfig.json is being reset and I am loosing all changes. Looking at targetcli - it is empty now
6. When I try to create block on any of those servers I am getting
gluster-block create test/fortest ha 2 192.168.1.15,192.168.1.16 1GiB
BLOCK with name: 'fortest' already EXIST
I could create new, not existing block without problems.

Why is this file being reset? What am I doing wrong? Shouldn't be there any warning about file overriding?

**Comment by softyn** [comment]
Hi again,
So seems not to be a bug. Adding simply 'targetcli restoreconfig' as startup script solves the problem. It just works this way.

**Comment by pkalever** [comment]
In general, after rebooting the server, you just need to make sure if your gluster volume is up and then systemctl start gluster-blockd, that should intern trigger gluster-block-target.service, which is responsible to load the target configuration from /etc/target/saveconfig.json.

Can you please confirm if this steps are working for you ?

If not, the must be a bug.
Please help with the environment details like, osversion, gluster-block/tcmu-runner/targetcli/rtslib/configshell versions ..., we will definitely take a look at it

Thanks for reporting this issue.

**Comment by pkalever** [comment]
@softyn ^^

**Comment by pkalever** [comment]
> So seems not to be a bug. Adding simply 'targetcli restoreconfig' as startup script solves the problem. It just works this way.

Cool;

Feel free to try the latest master (has lot many bug fixes) for better user experience.

Closing this now.
