### ISSUE TITLE
Do we get any performance benefits with aio/dio

### ISSUE THREAD

**Issue by pranithk** [gluster/gluster-block#99]
I saw the following pull request on rtslib(https://github.com/open-iscsi/rtslib-fb/pull/134) and wondering if it gives any performance benefit for gluster-block
@pkalever @lxbsz Do you guys know?

**Comment by lxbsz** [comment]
@pranithk @pkalever 
This fd_async_io option is only for the target/file(LIO/FILE), won't make any sense to the LIO/TCMU. 
Thanks.

**Comment by pkalever** [comment]
Thanks @lxbsz. closing it now.
